### ISSUE TITLE
https://angular.io/

### ISSUE THREAD

**Issue by obenjiro** [andreleon/critical-snapshot#1]
Uncaught DOMException: Failed to execute 'matches' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate)' is not a valid selector.
    at getNodeCSSRules (file:///Users/ookhrymenko/Library/Application%20Support/Google/Chrome%20Can…Extensions/gkoeffcejdhhojognlonafnijfkcepob/0.0.6_0/critical.min.js:1:1329)
    at r (file:///Users/ookhrymenko/Library/Application%20Support/Google/Chrome%20Can…Extensions/gkoeffcejdhhojognlonafnijfkcepob/0.0.6_0/critical.min.js:1:4681)
    at new CriticalSnapshot (file:///Users/ookhrymenko/Library/Application%20Support/Google/Chrome%20Can…Extensions/gkoeffcejdhhojognlonafnijfkcepob/0.0.6_0/critical.min.js:1:4856)
    at generatePopup (file:///Users/ookhrymenko/Library/Application%20Support/Google/Chrome%20Can…Extensions/gkoeffcejdhhojognlonafnijfkcepob/0.0.6_0/critical.min.js:1:3440)
    at file:///Users/ookhrymenko/Library/Application%20Support/Google/Chrome%20Can…Extensions/gkoeffcejdhhojognlonafnijfkcepob/0.0.6_0/critical.min.js:1:4861

function getNodeCSSRules(e) {
    var t, n, i, c, r = [];
    for (t = toArray(window.document.styleSheets); n = t.shift(); )
        for (i = getSheetRules(n); c = i.shift(); )
            c.styleSheet ? i = getSheetRules(c.styleSheet).concat(i) : c.media ? i = getSheetRules(c).concat(i) : e.matches(c.selectorText) && r.push(c); <-- HERE!
    return sortBySpecificity(e, r)
}

**Comment by andreleon** [comment]
Thanks! This is fixed in commit d137ac476361d0ff8d78650cf337c1545bb0fffa
